# Web with Mozila Firefox
xdg-mime default firefox.desktop x-scheme-handler/http
xdg-mime default firefox.desktop text/html
xdg-mime default firefox.desktop application/xhtml+xml
xdg-mime default firefox.desktop x-scheme-handler/https
# images with shotwell
xdg-mime default shotwell-viewer.desktop image/jpeg # jpeg
xdg-mime default shotwell-viewer.desktop image/jpg
xdg-mime default shotwell-viewer.desktop image/pjpeg
xdg-mime default shotwell-viewer.desktop image/png
xdg-mime default shotwell-viewer.desktop image/tiff
xdg-mime default shotwell-viewer.desktop image/x-3fr
xdg-mime default shotwell-viewer.desktop image/x-adobe-dng
xdg-mime default shotwell-viewer.desktop image/x-arw
xdg-mime default shotwell-viewer.desktop image/x-bay
xdg-mime default shotwell-viewer.desktop image/x-bmp
xdg-mime default shotwell-viewer.desktop image/x-canon-cr2
xdg-mime default shotwell-viewer.desktop image/x-canon-crw
xdg-mime default shotwell-viewer.desktop image/x-cap
xdg-mime default shotwell-viewer.desktop image/x-cr2
xdg-mime default shotwell-viewer.desktop image/x-crw
xdg-mime default shotwell-viewer.desktop image/x-dcr
xdg-mime default shotwell-viewer.desktop image/x-dcraw
xdg-mime default shotwell-viewer.desktop image/x-dcs
xdg-mime default shotwell-viewer.desktop image/x-dng
xdg-mime default shotwell-viewer.desktop image/x-drf
xdg-mime default shotwell-viewer.desktop image/x-eip
xdg-mime default shotwell-viewer.desktop image/x-erf
xdg-mime default shotwell-viewer.desktop image/x-fff
xdg-mime default shotwell-viewer.desktop image/x-fuji-raf
xdg-mime default shotwell-viewer.desktop image/x-iiq
xdg-mime default shotwell-viewer.desktop image/x-k25
xdg-mime default shotwell-viewer.desktop image/x-kdc
xdg-mime default shotwell-viewer.desktop image/x-mef
xdg-mime default shotwell-viewer.desktop image/x-minolta-mrw
xdg-mime default shotwell-viewer.desktop image/x-mos
xdg-mime default shotwell-viewer.desktop image/x-mrw
xdg-mime default shotwell-viewer.desktop image/x-nef
xdg-mime default shotwell-viewer.desktop image/x-nikon-nef
xdg-mime default shotwell-viewer.desktop image/x-nrw
xdg-mime default shotwell-viewer.desktop image/x-olympus-orf
xdg-mime default shotwell-viewer.desktop image/x-orf
xdg-mime default shotwell-viewer.desktop image/x-panasonic-raw
xdg-mime default shotwell-viewer.desktop image/x-pef
xdg-mime default shotwell-viewer.desktop image/x-pentax-pef
xdg-mime default shotwell-viewer.desktop image/x-png
xdg-mime default shotwell-viewer.desktop image/x-ptx
xdg-mime default shotwell-viewer.desktop image/x-pxn
xdg-mime default shotwell-viewer.desktop image/x-r3d
xdg-mime default shotwell-viewer.desktop image/x-raf
xdg-mime default shotwell-viewer.desktop image/x-raw
xdg-mime default shotwell-viewer.desktop image/x-rw2
xdg-mime default shotwell-viewer.desktop image/x-rwl
xdg-mime default shotwell-viewer.desktop image/x-rwz
xdg-mime default shotwell-viewer.desktop image/x-sigma-x3f
xdg-mime default shotwell-viewer.desktop image/x-sony-arw
xdg-mime default shotwell-viewer.desktop image/x-sony-sr2
xdg-mime default shotwell-viewer.desktop image/x-sony-srf
xdg-mime default shotwell-viewer.desktop image/x-sr2
xdg-mime default shotwell-viewer.desktop image/x-srf
xdg-mime default shotwell-viewer.desktop image/x-x3f
# videos with totem
xdg-mime default totem.desktop video/x-ogm+ogg # ogm+ogg
xdg-mime default totem.desktop video/3gp
xdg-mime default totem.desktop video/3gpp
xdg-mime default totem.desktop video/3gpp2
xdg-mime default totem.desktop video/dv
xdg-mime default totem.desktop video/divx
xdg-mime default totem.desktop video/fli
xdg-mime default totem.desktop video/flv
xdg-mime default totem.desktop video/mp2t
xdg-mime default totem.desktop video/mp4
xdg-mime default totem.desktop video/mp4v-es
xdg-mime default totem.desktop video/mpeg
xdg-mime default totem.desktop video/mpeg-system
xdg-mime default totem.desktop video/msvideo
xdg-mime default totem.desktop video/ogg
xdg-mime default totem.desktop video/quicktime
xdg-mime default totem.desktop video/vivo
xdg-mime default totem.desktop video/vnd.divx
xdg-mime default totem.desktop video/vnd.mpegurl
xdg-mime default totem.desktop video/vnd.rn-realvideo
xdg-mime default totem.desktop video/vnd.vivo
xdg-mime default totem.desktop video/webm
xdg-mime default totem.desktop video/x-anim
xdg-mime default totem.desktop video/x-avi
xdg-mime default totem.desktop video/x-flc
xdg-mime default totem.desktop video/x-fli
xdg-mime default totem.desktop video/x-flic
xdg-mime default totem.desktop video/x-flv
xdg-mime default totem.desktop video/x-m4v
xdg-mime default totem.desktop video/x-matroska
xdg-mime default totem.desktop video/x-mjpeg
xdg-mime default totem.desktop video/x-mpeg
xdg-mime default totem.desktop video/x-mpeg2
xdg-mime default totem.desktop video/x-ms-asf
xdg-mime default totem.desktop video/x-ms-asf-plugin
xdg-mime default totem.desktop video/x-ms-asx
xdg-mime default totem.desktop video/x-msvideo
xdg-mime default totem.desktop video/x-ms-wm
xdg-mime default totem.desktop video/x-ms-wmv
xdg-mime default totem.desktop video/x-ms-wmx
xdg-mime default totem.desktop video/x-ms-wvx
xdg-mime default totem.desktop video/x-nsv
xdg-mime default totem.desktop video/x-theora
xdg-mime default totem.desktop video/x-theora+ogg
xdg-mime default totem.desktop video/x-totem-stream
# audio with rhythmbox
xdg-mime default rhythmbox.desktop audio/x-vorbis+ogg
xdg-mime default rhythmbox.desktop audio/vorbis
xdg-mime default rhythmbox.desktop audio/x-vorbis
xdg-mime default rhythmbox.desktop audio/x-scpls
xdg-mime default rhythmbox.desktop audio/x-mp3
xdg-mime default rhythmbox.desktop audio/x-mpeg
xdg-mime default rhythmbox.desktop audio/mpeg
xdg-mime default rhythmbox.desktop audio/x-mpegurl
xdg-mime default rhythmbox.desktop audio/x-flac
xdg-mime default rhythmbox.desktop audio/mp4
xdg-mime default rhythmbox.desktop audio/x-it
xdg-mime default rhythmbox.desktop audio/x-mod
xdg-mime default rhythmbox.desktop audio/x-s3m
xdg-mime default rhythmbox.desktop audio/x-stm
xdg-mime default rhythmbox.desktop audio/x-xm
# books with evince
xdg-mime default org.gnome.Evince.desktop application/pdf
xdg-mime default org.gnome.Evince.desktop application/epub+zip
# zip with file-roller
xdg-mime default org.gnome.FileRoller.desktop application/zip
xdg-mime default org.gnome.FileRoller.desktop application/x-7z-compressed
xdg-mime default org.gnome.FileRoller.desktop application/x-rar
xdg-mime default org.gnome.FileRoller.desktop application/x-tar
xdg-mime default org.gnome.FileRoller.desktop application/gzip
# txt with gnome-text-editor
xdg-mime default org.gnome.TextEditor.desktop text/plain
# torrent with transmission-gtk
xdg-mime default transmission-gtk.desktop application/x-bittorrent
xdg-mime default transmission-gtk.desktop application/x-utorrent
# deb
xdg-mime default gdebi.desktop application/vnd.debian.binary-package