set -e                  # exit on error
set -o pipefail         # exit on pipeline error
set -u                  # treat unset variable as error

print_ok "Configuring locales and resolvconf..."
dpkg-reconfigure locales
dpkg-reconfigure resolvconf
judge "Configure locales and resolvconf"

print_ok "Configuring locales to $LANG..."
cat <<EOF > /etc/default/locale
# Generated by AnduinOS.
LANG=$LANG
EOF
judge "Configure locales to $LANG"